#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
$HOME/.screenlayout/monitor.sh &
feh --bg-scale $HOME/Pictures/wallpapers/.selected_wallpaper.png &
picom --blur-method gaussian &
sudo g810-led -p /etc/g810-led/gruvbox &
dunst &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap          20

#border colors
bspc config focused_border_color \#fe8019
bspc config normal_border_color \#fbf1c7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^3' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a Steam state=floating desktop='^5' follow=on
bspc rule -a discord desktop='^0' follow=on

# set monitor oritentation and tab labels
bspc monitor ^1 -s ^2
bspc monitor DP-4 -d     
bspc monitor HDMI-0 -d 6 7 8 9 
